# Generated by Django 3.0.3 on 2020-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
