# Generated by Django 3.0.3 on 2020-03-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube',
        ),
    ]
