# Generated by Django 3.0.3 on 2020-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftute',
            name='cetogory',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
