# Generated by Django 3.0.3 on 2020-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownload', '0002_pdftute_cetogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdftute',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='pdftute',
            name='slug',
        ),
    ]
