# Generated by Django 3.0.3 on 2020-05-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownload', '0003_auto_20200516_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftute',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
