# Generated by Django 3.0.3 on 2020-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownload', '0004_auto_20200516_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftute',
            name='description',
            field=models.TextField(),
        ),
    ]
