# Generated by Django 3.0.3 on 2020-05-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownload', '0005_auto_20200516_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftute',
            name='cetogory',
        ),
    ]
